### ISSUE TITLE
Server Sends Back Error When Attempting To Vote For 2 Places

### ISSUE THREAD

**Issue by reid-harrison** [mjm/sis-lunch#7]
Firebug XML and Response:

XML Parsing Error: mismatched tag. Expected: </meta>. Location: moz-nullprincipal:{6cd605ec-65ea-4a42-b699-fa4b6b332350} Line Number 9, Column 39:

```
<title>Application Error</title></head>
```

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
    <html>
    <head>
      <meta http-equiv="content-type" content="text/html; charset=ISO-8859-1">
      <style type="text/css">
        html, body, iframe { margin: 0; padding: 0; height: 100%; }
        iframe { display: block; width: 100%; border: none; }
      </style>
    <title>Application Error</title></head>
    </head>
    <body>
      <iframe src="https://s3.amazonaws.com/heroku_pages/error.html">
        <p>Application Error</p>
      </iframe>
    </body>
    </html>

If you have already voted on a place and then you attempt to vote on another Firebug shows an error. Maybe vote buttons should be hidden if you've already voted for something.

**Comment by mjm** [comment]
This has to do with not checking validation well, but since there is an intention to make multiple votes allowed, I'm not going to bother with this.
